<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>_10 Negara Penerbit Passport</name>
   <tag></tag>
   <elementGuidId>16c80014-8844-41ce-96f8-66698d28b238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ContentPlaceHolder1_RP_CountryPassport-inputEl&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_RP_EntireForm-innerCt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>innerCt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-autocontainer-innerCt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ID:AutoNumberKode Laporan:Nama Lengkap:This field is requiredInput error. This field is required.This field is requiredTanggal Lahir:Expected date format n/j/Y.This field is requiredInput error. This field is required.This field is requiredTempat Lahir:Jenis Kelamin:This field is requiredInput error. This field is required.This field is requiredNama Ibu Kandung:Nama Alias:NIK:No. Paspor:Negara Penerbit Paspor:No. Identitas Lainnya:IdentificationIdentity DataAdd New IdentityJenis identitasCell value has been editedNomor identitasCell value has been editedNegara penerbit identitasCell value has been editedActionCell value has been editedNo Available Data PhonePhone DataAdd New PhoneKategori KontakCell value has been editedJenis Alat KomunikasiCell value has been editedNomor TeleponCell value has been editedActionCell value has been editedNo Available Data AddressAddress DataAdd New AddressTipe AlamatCell value has been editedAlamatCell value has been editedKota/KabupatenCell value has been editedNegaraCell value has been editedActionCell value has been editedNo Available Data Kewarganegaraan 1:Kewarganegaraan 2:Kewarganegaraan 3:Negara Domisili:Email 1:Email 2:Email 3:Email 4:Email 5:Pekerjaan:Tempat Bekerja:Sudah Meninggal?:Tanggal Meninggal:Expected date format n/j/Y.NPWP:PEPs?:Sumber Dana:Catatan:</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_RP_EntireForm-innerCt&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parameter/Reporting Person/1/iframe_Datamart_nodeundefined_IFrame</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_RP_EntireForm-innerCt']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_RP_EntireForm-outerCt']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reporting Person'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
