'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AuditTrail_UserLogin
    Public Property UserLoginID As Long
    Public Property UserLoginUserid As String
    Public Property UserLoginActionDate As Nullable(Of Date)
    Public Property UserLoginAction As String
    Public Property UserLoginIPAddress As String
    Public Property UserLoginDescription As String

End Class
