'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AuditTrailHeader
    Public Property PK_AuditTrail_ID As Long
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property ApproveBy As String
    Public Property ModuleLabel As String
    Public Property FK_ModuleAction_ID As Nullable(Of Integer)
    Public Property FK_AuditTrailStatus_ID As Nullable(Of Integer)
    Public Property PK_ModuleApproval_ID As Nullable(Of Long)

    Public Overridable Property AuditTrailDetails As ICollection(Of AuditTrailDetail) = New HashSet(Of AuditTrailDetail)

End Class
