'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AuditTrail_UserAccess
    Public Property PK_UserAccessID As Long
    Public Property Userid As String
    Public Property ActionDate As Nullable(Of Date)
    Public Property Action As String

End Class
