'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CleansingReport
    Public Property PK_Record_ID As Long
    Public Property SegmentData As String
    Public Property KeyField As String
    Public Property KeyFieldValue As String
    Public Property NamaField As String
    Public Property OriginalValue As String
    Public Property CleanedValue As String
    Public Property Status As String
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property LastUpdateBy As String
    Public Property ApprovedBy As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property LastUpdateDate As Nullable(Of Date)
    Public Property ApprovedDate As Nullable(Of Date)
    Public Property UniqueField As String
    Public Property UniqueValue As String
    Public Property ModuleID As String
    Public Property ModuleName As String
    Public Property Clean As Nullable(Of Boolean)
    Public Property Keep As Nullable(Of Boolean)
    Public Property FieldName As String
    Public Property Report_Date As Nullable(Of Date)
    Public Property Kode_Cabang_BI As String
    Public Property CleansingRules As String

End Class
