'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ELMAH_Error
    Public Property ErrorId As System.Guid
    Public Property Application As String
    Public Property Host As String
    Public Property Type As String
    Public Property Source As String
    Public Property Message As String
    Public Property User As String
    Public Property StatusCode As Integer
    Public Property TimeUtc As Date
    Public Property Sequence As Integer
    Public Property AllXml As String

End Class
