'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmailTemplate
    Public Property PK_EmailTemplate_ID As Integer
    Public Property EmailTemplateName As String
    Public Property EmailTo As String
    Public Property EmailCC As String
    Public Property EmailBCC As String
    Public Property EmailSubject As String
    Public Property EmailBody As String
    Public Property FK_Monitoringduration_ID As Nullable(Of Integer)
    Public Property StartDate As Nullable(Of Date)
    Public Property StartTime As String
    Public Property ExcludeHoliday As Nullable(Of Boolean)
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property LastUpdateBy As String
    Public Property ApprovedBy As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property LastUpdateDate As Nullable(Of Date)
    Public Property ApprovedDate As Nullable(Of Date)
    Public Property IsSupportEmail As Nullable(Of Boolean)
    Public Property IsSupportNotification As Nullable(Of Boolean)

    Public Overridable Property MonitoringDuration As MonitoringDuration

End Class
