'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmailTemplateScheduler
    Public Property PK_EmailTemplateScheduler_ID As Long
    Public Property PK_EmailTemplate_ID As Nullable(Of Long)
    Public Property ProcessDate As Nullable(Of Date)
    Public Property FK_EmailStatus_ID As Nullable(Of Integer)

End Class
