'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmailTemplateSchedulerDetail
    Public Property PK_EmailTemplateSchedulerDetail_ID As Long
    Public Property FK_EmailTEmplateScheduler_ID As Nullable(Of Long)
    Public Property UnikFieldTablePrimary As String
    Public Property EmailTo As String
    Public Property EmailCC As String
    Public Property EmailBCC As String
    Public Property EmailSubject As String
    Public Property EmailBody As String
    Public Property ProcessDate As Nullable(Of Date)
    Public Property SendEmailDate As Nullable(Of Date)
    Public Property FK_EmailStatus_ID As Nullable(Of Integer)
    Public Property ErrorMessage As String
    Public Property retrycount As Nullable(Of Integer)
    Public Property EmailID As String
    Public Property resendByUserCount As Integer
    Public Property EmailIDReference As String

End Class
