'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileSecurity
    Public Property FileSecurityID As Integer
    Public Property FileSecurityGroupId As Nullable(Of Integer)
    Public Property FileSecurityFileName As String

    Public Overridable Property MGroupMenu As MGroupMenu

End Class
