'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GenerateFileTemplateAdditional
    Public Property PK_GenerateFileTemplateAdditional_ID As Long
    Public Property FK_GenerationFileTemplate_ID As Nullable(Of Long)
    Public Property SQLQuery As String
    Public Property [Alias] As String
    Public Property UnikField As String
    Public Property OutputFormat As String
    Public Property TableSource As String
    Public Property TanggalData As String
    Public Property RecordId As String
    Public Property KodeCabang As String

End Class
