'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GenerateFileTemplateDetail
    Public Property PK_GenerateFileTemplateDetail_ID As Long
    Public Property FK_GenerationFileTemplate_ID As Nullable(Of Integer)
    Public Property Replacer As String
    Public Property FieldReplacer As String

End Class
