'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MenuTemplate
    Public Property mMenuID As String
    Public Property mMenuLabel As String
    Public Property mMenuParentID As String
    Public Property mMenuURL As String
    Public Property FK_Module_ID As Nullable(Of Integer)
    Public Property FK_Action_ID As Nullable(Of Integer)
    Public Property urutan As Nullable(Of Integer)

End Class
