'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MExtType
    Public Property PK_ExtType_ID As Integer
    Public Property ExtTypeName As String
    Public Property ExtTypeDesc As String

    Public Overridable Property ModuleFields As ICollection(Of ModuleField) = New HashSet(Of ModuleField)

End Class
