'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MFieldType
    Public Property PK_FieldType_ID As Integer
    Public Property FieldTypeCaption As String
    Public Property FieldTypeDescription As String
    Public Property FieldTypeSQLName As String
    Public Property FieldTypeNetName As String
    Public Property CodeEffecttype As String
    Public Property CodeEffectNETType As String

    Public Overridable Property ModuleFields As ICollection(Of ModuleField) = New HashSet(Of ModuleField)

End Class
