'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MGroupMenuAccess
    Public Property PK_MGroupMenuAcess_ID As Integer
    Public Property FK_GroupMenu_ID As Nullable(Of Integer)
    Public Property FK_Module_ID As Nullable(Of Integer)
    Public Property bAdd As Nullable(Of Boolean)
    Public Property bEdit As Nullable(Of Boolean)
    Public Property bDelete As Nullable(Of Boolean)
    Public Property bActivation As Nullable(Of Boolean)
    Public Property bView As Nullable(Of Boolean)
    Public Property bApproval As Nullable(Of Boolean)
    Public Property bUpload As Nullable(Of Boolean)
    Public Property bDetail As Nullable(Of Boolean)

End Class
