'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ModuleField
    Public Property PK_ModuleField_ID As Long
    Public Property FK_Module_ID As Nullable(Of Integer)
    Public Property FieldName As String
    Public Property FieldLabel As String
    Public Property Sequence As Nullable(Of Integer)
    Public Property Required As Nullable(Of Boolean)
    Public Property IsPrimaryKey As Nullable(Of Boolean)
    Public Property IsUnik As Nullable(Of Boolean)
    Public Property IsShowInView As Nullable(Of Boolean)
    Public Property FK_FieldType_ID As Nullable(Of Integer)
    Public Property SizeField As Nullable(Of Integer)
    Public Property FK_ExtType_ID As Nullable(Of Integer)
    Public Property TabelReferenceName As String
    Public Property TableReferenceFieldKey As String
    Public Property TableReferenceFieldDisplayName As String
    Public Property TableReferenceFilter As String
    Public Property IsUseRegexValidation As Nullable(Of Boolean)
    Public Property TabelReferenceNameAlias As String
    Public Property IsShowInForm As Nullable(Of Boolean)
    Public Property DefaultValue As String
    Public Property TableReferenceAdditonalJoin As String
    Public Property BCasCade As Nullable(Of Boolean)
    Public Property FieldNameParent As String
    Public Property FilterCascade As String

    Public Overridable Property MExtType As MExtType
    Public Overridable Property MFieldType As MFieldType
    Public Overridable Property [Module] As [Module]
    Public Overridable Property ModuleFieldRegexes As ICollection(Of ModuleFieldRegex) = New HashSet(Of ModuleFieldRegex)

End Class
