'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ModuleFieldRegex
    Public Property PK_ModuleFieldRegex As Long
    Public Property FK_ModuleField_ID As Nullable(Of Long)
    Public Property Regex As String

    Public Overridable Property ModuleField As ModuleField

End Class
