'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ModuleFieldDefault
    Public Property PK_ModuleField_ID As Long
    Public Property FieldName As String
    Public Property FieldLabel As String
    Public Property Sequence As Nullable(Of Integer)
    Public Property Required As Nullable(Of Boolean)
    Public Property IsPrimaryKey As Nullable(Of Boolean)
    Public Property IsUnik As Nullable(Of Boolean)
    Public Property FK_FieldType_ID As Nullable(Of Integer)
    Public Property SizeField As Nullable(Of Integer)
    Public Property FK_ExtType_ID As Nullable(Of Integer)

End Class
