'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class [Module]
    Public Property PK_Module_ID As Integer
    Public Property ModuleName As String
    Public Property ModuleLabel As String
    Public Property ModuleDescription As String
    Public Property IsUseDesigner As Nullable(Of Boolean)
    Public Property IsUseApproval As Nullable(Of Boolean)
    Public Property IsSupportAdd As Nullable(Of Boolean)
    Public Property IsSupportEdit As Nullable(Of Boolean)
    Public Property IsSupportDelete As Nullable(Of Boolean)
    Public Property IsSupportActivation As Nullable(Of Boolean)
    Public Property IsSupportView As Nullable(Of Boolean)
    Public Property IsSupportUpload As Nullable(Of Boolean)
    Public Property IsSupportDetail As Nullable(Of Boolean)
    Public Property UrlAdd As String
    Public Property UrlEdit As String
    Public Property UrlDelete As String
    Public Property UrlActivation As String
    Public Property UrlView As String
    Public Property UrlUpload As String
    Public Property UrlApproval As String
    Public Property UrlApprovalDetail As String
    Public Property UrlDetail As String
    Public Property IsUseStoreProcedureValidation As Nullable(Of Boolean)
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property LastUpdateBy As String
    Public Property ApprovedBy As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property LastUpdateDate As Nullable(Of Date)
    Public Property ApprovedDate As Nullable(Of Date)

    Public Overridable Property ModuleFields As ICollection(Of ModuleField) = New HashSet(Of ModuleField)
    Public Overridable Property ModuleValidations As ICollection(Of ModuleValidation) = New HashSet(Of ModuleValidation)

End Class
