'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ModuleAction
    Public Property PK_ModuleAction_ID As Integer
    Public Property ModuleActionName As String
    Public Property ModuleActionDescription As String

    Public Overridable Property ModuleValidations As ICollection(Of ModuleValidation) = New HashSet(Of ModuleValidation)

End Class
