'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ModuleValidation
    Public Property PK_ModuleValidation_ID As Integer
    Public Property FK_Module_ID As Nullable(Of Integer)
    Public Property FK_ModuleAction_ID As Nullable(Of Integer)
    Public Property FK_ModuleTime_ID As Nullable(Of Integer)
    Public Property StoreProcedureName As String
    Public Property StoreProcedureParameter As String
    Public Property StoreProcedureParameterValueFieldSequence As String

    Public Overridable Property [Module] As [Module]
    Public Overridable Property ModuleAction As ModuleAction
    Public Overridable Property ModuleTime As ModuleTime

End Class
