'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ModuleApproval
    Public Property PK_ModuleApproval_ID As Long
    Public Property ModuleName As String
    Public Property ModuleKey As String
    Public Property ModuleField As String
    Public Property ModuleFieldBefore As String
    Public Property PK_ModuleAction_ID As Nullable(Of Integer)
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy As String

End Class
