'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MRole_Upload
    Public Property PK_upload_ID As Long
    Public Property nawa_userid As String
    Public Property nawa_recordnumber As Nullable(Of Long)
    Public Property KeteranganError As String
    Public Property nawa_Action As String
    Public Property PK_MRole_ID As String
    Public Property RoleName As String
    Public Property RoleDescription As String
    Public Property Active As Nullable(Of Boolean)

End Class
