'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ORS_FormInfo
    Public Property Kode As String
    Public Property Nama As String
    Public Property FK_Module_ID As Nullable(Of Integer)
    Public Property KeyField As String
    Public Property KeyValue As String
    Public Property Periode As String
    Public Property DisplayField As String
    Public Property FK_DataSet As Nullable(Of Integer)
    Public Property FK_KelompokInformasi As String
    Public Property VersionCode As String
    Public Property NoUrut As Nullable(Of Integer)
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property LastUpdateBy As String
    Public Property ApprovedBy As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property LastUpdateDate As Nullable(Of Date)
    Public Property ApprovedDate As Nullable(Of Date)
    Public Property Alternateby As String
    Public Property InformationID As String
    Public Property PeriodePelaporan As String
    Public Property DataDateDiffH As Nullable(Of Integer)
    Public Property FK_GenerateType As String
    Public Property TanggalTepatWaktuAkhir As Nullable(Of Integer)
    Public Property JamTepatWaktuAkhir As Nullable(Of Integer)
    Public Property TanggalKoreksiAkhir As Nullable(Of Integer)
    Public Property JamKoreksiAkhir As Nullable(Of Integer)
    Public Property TanggalKeterlambatanAkhir As Nullable(Of Integer)
    Public Property JamKeterlambatanAkhir As Nullable(Of Integer)

End Class
