'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ReportofDisableName
    Public Property UserID As String
    Public Property UserName As String
    Public Property UserEmailAddress As String
    Public Property LastLogin As Nullable(Of Date)
    Public Property LastLoginInDays As Nullable(Of Integer)

End Class
