'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TextFileTemporaryTableDetail
    Public Property FK_TextFileTemporaryTable_ID As Integer
    Public Property Line As Integer
    Public Property Data As String
    Public Property Message As String

    Public Overridable Property TextFileTemporaryTable As TextFileTemporaryTable

End Class
