'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TextFileTemporaryTable
    Public Property Pk_TextFileTemporaryTable_ID As Integer
    Public Property FileName As String
    Public Property FK_FormInfo_ID As String
    Public Property DataSource As String
    Public Property TanggalData As Date
    Public Property Status As String
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property TotalRecord As Nullable(Of Integer)
    Public Property ErrorMessage As String
    Public Property Data As Byte()

    Public Overridable Property TextFileTemporaryTableDetails As ICollection(Of TextFileTemporaryTableDetail) = New HashSet(Of TextFileTemporaryTableDetail)

End Class
