'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ValidationParameter
    Public Property PK_ValidationParameter As Integer
    Public Property TableName As Integer
    Public Property FieldName As String
    Public Property ExpressionType As String
    Public Property ValidationExpression As String
    Public Property Description As String
    Public Property ValidationMessage As String
    Public Property ValidationType As Integer
    Public Property ErrorType As String
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property LastUpdateBy As String
    Public Property ApprovedBy As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property LastUpdateDate As Nullable(Of Date)
    Public Property ApprovedDate As Nullable(Of Date)
    Public Property Alternateby As String
    Public Property Fk_Ref_DataSet_Id As Nullable(Of Integer)
    Public Property Fk_Ref_KategoriValidasi_Id As Nullable(Of Integer)

End Class
