'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vw_KelompokInformasiRelation
    Public Property SandiKelompokInformasi As String
    Public Property KelompokInformasi As String
    Public Property SandiJenisLaporanInformasi As Decimal
    Public Property JenisLaporanInformasi As String
    Public Property FK_Module_ID As Nullable(Of Integer)
    Public Property Nama As String

End Class
