'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_MappingCounterparty
    Public Property PK_MappingCounterparty_ID As Integer
    Public Property ProductFamily As String
    Public Property CounterpartyName As String
    Public Property PergerakanDana As Nullable(Of Boolean)
    Public Property PihakTerkait As Nullable(Of Boolean)
    Public Property Bank As Nullable(Of Boolean)
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property LastUpdateBy As String
    Public Property ApprovedBy As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property LastUpdateDate As Nullable(Of Date)
    Public Property ApprovedDate As Nullable(Of Date)
    Public Property Alternateby As String

End Class
