'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_TextFileTemporaryTable
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property TotalRecord As Nullable(Of Integer)
    Public Property ErrorMessage As String
    Public Property Pk_ORS_TextFileTemporaryTable_ID As Long
    Public Property UploadFileName As String
    Public Property ModuleLabel As String
    Public Property Report_Date As Nullable(Of Date)
    Public Property StatusUpload As String

End Class
