'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_ValidationReport
    Public Property TanggalData As Date
    Public Property SegmentData As String
    Public Property NamaField As String
    Public Property ValidationMessage As String
    Public Property KeyFieldValue As String
    Public Property KeyField As String
    Public Property ModuleURL As String
    Public Property RecordID As String
    Public Property ModuleID As Nullable(Of Integer)
    Public Property ValidationType As String
    Public Property ID As Integer

End Class
