'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GeneratedFileList
    Public Property PK_GeneratedFileList_ID As Long
    Public Property TanggalData As Nullable(Of Date)
    Public Property FK_LHBU_FormInfo_ID As String
    Public Property FileName As String
    Public Property FileType As String
    Public Property FileBin As Byte()
    Public Property StartDate As Nullable(Of Date)
    Public Property CompleteDate As Nullable(Of Date)
    Public Property ErrorMsg As String
    Public Property Comment As String
    Public Property GenerationStatus As String
    Public Property ApprovalStatus As String
    Public Property CreatedBy As String
    Public Property UpdatedBy As String
    Public Property ApprovedBy As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property UpdatedDate As Nullable(Of Date)
    Public Property ApprovedDate As Nullable(Of Date)
    Public Property SubmitStatus As String
    Public Property SubmitNote As String
    Public Property TotalData As Nullable(Of Integer)
    Public Property KodeCabang As String
    Public Property FK_Template_ID As Nullable(Of Integer)
    Public Property Request_ID As Nullable(Of Integer)

End Class
