'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NawadataConnectionString
    Public Property PK_NawaDataConnectionString_ID As Integer
    Public Property ConnecitonName As String
    Public Property ConnectionValue As String
    Public Property PasswordValue As String
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property LastUpdateBy As String
    Public Property ApprovedBy As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property LastUpdateDate As Nullable(Of Date)
    Public Property ApprovedDate As Nullable(Of Date)
    Public Property Alternateby As String
    Public Property PasswordValue1 As String
    Public Property PasswordEncript As String
    Public Property PasswordBinary As Byte()
    Public Property PasswordBinaryName As String

End Class
