'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vw_GeneratedFileList
    Public Property Request_ID As Nullable(Of Integer)
    Public Property PK_GeneratedFileList_ID As Long
    Public Property PeriodeLaporan As Nullable(Of Date)
    Public Property KodeCabang As String
    Public Property FK_LHBU_FormInfo_ID As String
    Public Property FormInfo As String
    Public Property FK_Template_ID As Nullable(Of Integer)
    Public Property GenerateFileTemplateName As String
    Public Property FileName As String
    Public Property FileType As String
    Public Property StartDate As Nullable(Of Date)
    Public Property CompleteDate As Nullable(Of Date)
    Public Property ErrorMsg As String
    Public Property Comment As String
    Public Property GenerationStatus As String
    Public Property ApprovalStatus As String
    Public Property SubmitStatus As String
    Public Property SubmitNote As String
    Public Property TotalData As Nullable(Of Integer)

End Class
